### ISSUE TITLE
Example for rule prediction at different check points

### ISSUE THREAD

**Issue by prakashtewari** [ryanurbs/eLCS#1]
Hi, 
thanks for the great package. 

I was wondering if it is possible to create a test example to output the results at different checkpoints in the config file. 

For example, if we can get output for 6Multiplexer dataset at checkpoints, say 1000 and 2000. This will help in visualizing the results and checking accuracy. 

thanks in advance

**Comment by ryanurbs** [comment]
Hi prakashtewari, all you'd have to do is edit the file 'eLCS_Configuration_File.txt'.  Just change learningIterations=5000.10000	 to learningIterations=1000.2000

This will output checkpoint analyses after only 1000 and 2000 runs.
